// Fetch HDB carpark info from data.gov.sg and bake it into js/hdbCarparks.js
// so the browser no longer makes a live API call at runtime (the public API
// rate-limits by IP, which was ~50/50 failing on GitHub Pages).
//
// Run: node scripts/buildHdbCarparks.mjs
// Re-run whenever you want to refresh the bundled snapshot (rarely needed).

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");
const OUT = join(ROOT, "js", "hdbCarparks.js");
const URL = "https://data.gov.sg/api/action/datastore_search?resource_id=d_23f946fa557947f93a8043bbef41dd09&limit=2500";

// SVY21 -> WGS84 (identical math to js/svy21.js, inlined so the build is standalone)
const a = 6378137;
const f = 1 / 298.257223563;
const oLat = 1.366666;
const oLon = 103.833333;
const oN = 38744.572;
const oE = 28001.642;
const e2 = 2 * f - f * f;
const e4 = e2 * e2;
const e6 = e4 * e2;
const A0 = 1 - e2 / 4 - 3 * e4 / 64 - 5 * e6 / 256;
const A2 = (3 / 8) * (e2 + e4 / 4 + 15 * e6 / 128);
const A4 = (15 / 256) * (e4 + 3 * e6 / 4);
const A6 = 35 * e6 / 3072;
const DEG = Math.PI / 180;

function calcM(latRad) {
  return a * (A0 * latRad - A2 * Math.sin(2 * latRad) + A4 * Math.sin(4 * latRad) - A6 * Math.sin(6 * latRad));
}
function svy21ToLatLon(N, E) {
  const Nprime = N - oN;
  const Mo = calcM(oLat * DEG);
  const M = Mo + Nprime / 1.0;
  const mu = M / (a * A0);
  const e1 = (1 - Math.sqrt(1 - e2)) / (1 + Math.sqrt(1 - e2));
  const latRad = mu
    + (3 * e1 / 2 - 27 * e1 ** 3 / 32) * Math.sin(2 * mu)
    + (21 * e1 ** 2 / 16 - 55 * e1 ** 4 / 32) * Math.sin(4 * mu)
    + (151 * e1 ** 3 / 96) * Math.sin(6 * mu)
    + (1097 * e1 ** 4 / 512) * Math.sin(8 * mu);
  const sinLat = Math.sin(latRad);
  const cosLat = Math.cos(latRad);
  const rho = a * (1 - e2) / Math.pow(1 - e2 * sinLat * sinLat, 1.5);
  const nu = a / Math.sqrt(1 - e2 * sinLat * sinLat);
  const psi = nu / rho;
  const t = Math.tan(latRad);
  const Eprime = E - oE;
  const x = Eprime;
  const lat = latRad
    - (t / rho) * (x * x / (2 * nu))
    + (t / rho) * (x ** 4 / (24 * nu ** 3)) * (-4 * psi * psi + 9 * psi * (1 - t * t) + 12 * t * t);
  const sec = 1 / cosLat;
  const lon = oLat * 0 + oLon * DEG
    + sec * (x / nu)
    - sec * (x ** 3 / (6 * nu ** 3)) * (psi + 2 * t * t)
    + sec * (x ** 5 / (120 * nu ** 5)) * (-4 * psi ** 3 * (1 - 6 * t * t) + psi * psi * (9 - 68 * t * t) + 72 * psi * t * t + 24 * t ** 4);
  return { lat: lat / DEG, lng: lon / DEG };
}

async function fetchWithRetry(url, attempts = 20) {
  for (let i = 1; i <= attempts; i++) {
    const r = await fetch(url);
    if (r.ok) return r.json();
    if (r.status === 429) {
      console.log(`  [${i}/${attempts}] 429 rate-limited, waiting 30s...`);
      await new Promise((res) => setTimeout(res, 30000));
      continue;
    }
    throw new Error(`HTTP ${r.status}`);
  }
  throw new Error("rate limit did not clear");
}

async function main() {
  console.log("Fetching HDB carpark info from data.gov.sg...");
  const json = await fetchWithRetry(URL);
  const records = json.result?.records || [];
  console.log(`  got ${records.length} records`);

  const converted = records
    .map((r) => {
      const x = parseFloat(r.x_coord);
      const y = parseFloat(r.y_coord);
      if (!isFinite(x) || !isFinite(y)) return null;
      const { lat, lng } = svy21ToLatLon(y, x);
      return {
        car_park_no: r.car_park_no,
        name: `HDB ${r.car_park_no}`,
        address: r.address,
        lat: +lat.toFixed(7),
        lng: +lng.toFixed(7),
        car_park_type: r.car_park_type,
        short_term_parking: r.short_term_parking,
        night_parking_available: r.night_parking === "YES",
        kind: "hdb",
      };
    })
    .filter(Boolean);

  const body = `// Auto-generated by scripts/buildHdbCarparks.mjs from data.gov.sg
// resource_id=d_23f946fa557947f93a8043bbef41dd09  entries=${converted.length}
// Regenerate with: node scripts/buildHdbCarparks.mjs

window.HDB_CARPARKS = ${JSON.stringify(converted, null, 2)};
`;
  writeFileSync(OUT, body);
  console.log(`Wrote ${OUT} with ${converted.length} entries.`);
}

main().catch((e) => { console.error(e); process.exit(1); });
